version: '2'
services:
    njmuseum-app:
        image: njmuseum
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://njmuseum-mysql:3306/njmuseum?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    njmuseum-mysql:
        extends:
            file: mysql.yml
            service: njmuseum-mysql
